### ISSUE TITLE
Some badges are showing up as invisible

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/YesEquality#10]
After 6 taps and after 8 taps, those two badges are invisible. iOS 7 and 8

**Comment by adam-govan** [comment]
I can't seem to get my iPhone to build this since it won't stop raging about the Team ID. (I have no idea, xcode 6 is annoying me) anyway, the images in the badges part, the ones you were talking about: YES_white and TA_white are both unassigned. so they're empty. that would explain the issue. 

I can't verify on my device though.

**Comment by adam-govan** [comment]
you can see this (on the master branch at least) in 'Badges' in the Images.xcassets file.

**Comment by adam-govan** [comment]
I had to delete the tests folder to test locally, but it worked. I then reset and applied the changes to the following branch. 

https://github.com/HackForEquality/YesEquality/tree/bug-fixes
